### ISSUE TITLE
Guarantee stability for -twt_groupWithBlock:

### ISSUE THREAD

**Issue by macdrevx** [twotoasters/Toast#70]
Currently, `-twt_groupWithBlock:` returns stable results. Consider the example given in the documentation:

> Given a collection of [2, 3, 6, 7, 9] and a block that returns the element’s integer value modulo 2, this method will return { 0 : [2, 6], 1 : { [3, 7, 9] } }.

I propose that the documentation explicitly guarantee that the result will preserve the ordering of elements in each result group relative to their ordering in the receiver (assuming the receiver is an ordered collection). Using the same example, this guarantee would preclude the result `{ 0 : [6, 2], 1 : { [9, 3, 7] } }`.

**Comment by macdrevx** [comment]
@prachigauriar happy to make a pull request to update the docs, but wanted to get your thoughts on this first.

**Comment by prachigauriar** [comment]
@macdrevx I think this is fine. Feel free to open a PR.

**Comment by prachigauriar** [comment]
A test case would be nice too.

**Comment by macdrevx** [comment]
This was resolved by #71
